services:
  postgres_db_poc:
    image: postgres:15
    container_name: postgres_db_container_poc
    restart: always
    environment:
      POSTGRES_USER: user_poc
      POSTGRES_PASSWORD: password_poc
      POSTGRES_DB: populationdb_poc
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_poc:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_poc -d populacaodb_poc"]
      interval: 10s
      timeout: 5s
      retries: 5

  population_app_poc:
    container_name: populacao_app_container_poc
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_CONNECTION_STRING: "Host=postgres_db_poc;Port=5432;Database=populacaodb_poc;Username=user_poc;Password=password_poc"
    depends_on:
      postgres_db_poc:
        condition: service_healthy 

volumes:
  postgres_data_poc:
    driver: local